# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hades/Projects/Space-Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hades/Projects/Space-Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hades/Projects/Space-Engine/CMakeFiles /home/hades/Projects/Space-Engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hades/Projects/Space-Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameEngine

# Build rule for target.
GameEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GameEngine
.PHONY : GameEngine

# fast build rule for target.
GameEngine/fast:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/build
.PHONY : GameEngine/fast

src/GameEngine/EngineInstance.o: src/GameEngine/EngineInstance.cpp.o
.PHONY : src/GameEngine/EngineInstance.o

# target to build an object file
src/GameEngine/EngineInstance.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/EngineInstance.cpp.o
.PHONY : src/GameEngine/EngineInstance.cpp.o

src/GameEngine/EngineInstance.i: src/GameEngine/EngineInstance.cpp.i
.PHONY : src/GameEngine/EngineInstance.i

# target to preprocess a source file
src/GameEngine/EngineInstance.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/EngineInstance.cpp.i
.PHONY : src/GameEngine/EngineInstance.cpp.i

src/GameEngine/EngineInstance.s: src/GameEngine/EngineInstance.cpp.s
.PHONY : src/GameEngine/EngineInstance.s

# target to generate assembly for a file
src/GameEngine/EngineInstance.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/EngineInstance.cpp.s
.PHONY : src/GameEngine/EngineInstance.cpp.s

src/GameEngine/Logger.o: src/GameEngine/Logger.cpp.o
.PHONY : src/GameEngine/Logger.o

# target to build an object file
src/GameEngine/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Logger.cpp.o
.PHONY : src/GameEngine/Logger.cpp.o

src/GameEngine/Logger.i: src/GameEngine/Logger.cpp.i
.PHONY : src/GameEngine/Logger.i

# target to preprocess a source file
src/GameEngine/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Logger.cpp.i
.PHONY : src/GameEngine/Logger.cpp.i

src/GameEngine/Logger.s: src/GameEngine/Logger.cpp.s
.PHONY : src/GameEngine/Logger.s

# target to generate assembly for a file
src/GameEngine/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Logger.cpp.s
.PHONY : src/GameEngine/Logger.cpp.s

src/GameEngine/Material.o: src/GameEngine/Material.cpp.o
.PHONY : src/GameEngine/Material.o

# target to build an object file
src/GameEngine/Material.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Material.cpp.o
.PHONY : src/GameEngine/Material.cpp.o

src/GameEngine/Material.i: src/GameEngine/Material.cpp.i
.PHONY : src/GameEngine/Material.i

# target to preprocess a source file
src/GameEngine/Material.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Material.cpp.i
.PHONY : src/GameEngine/Material.cpp.i

src/GameEngine/Material.s: src/GameEngine/Material.cpp.s
.PHONY : src/GameEngine/Material.s

# target to generate assembly for a file
src/GameEngine/Material.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Material.cpp.s
.PHONY : src/GameEngine/Material.cpp.s

src/GameEngine/MaterialManager.o: src/GameEngine/MaterialManager.cpp.o
.PHONY : src/GameEngine/MaterialManager.o

# target to build an object file
src/GameEngine/MaterialManager.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/MaterialManager.cpp.o
.PHONY : src/GameEngine/MaterialManager.cpp.o

src/GameEngine/MaterialManager.i: src/GameEngine/MaterialManager.cpp.i
.PHONY : src/GameEngine/MaterialManager.i

# target to preprocess a source file
src/GameEngine/MaterialManager.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/MaterialManager.cpp.i
.PHONY : src/GameEngine/MaterialManager.cpp.i

src/GameEngine/MaterialManager.s: src/GameEngine/MaterialManager.cpp.s
.PHONY : src/GameEngine/MaterialManager.s

# target to generate assembly for a file
src/GameEngine/MaterialManager.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/MaterialManager.cpp.s
.PHONY : src/GameEngine/MaterialManager.cpp.s

src/GameEngine/Mesh.o: src/GameEngine/Mesh.cpp.o
.PHONY : src/GameEngine/Mesh.o

# target to build an object file
src/GameEngine/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Mesh.cpp.o
.PHONY : src/GameEngine/Mesh.cpp.o

src/GameEngine/Mesh.i: src/GameEngine/Mesh.cpp.i
.PHONY : src/GameEngine/Mesh.i

# target to preprocess a source file
src/GameEngine/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Mesh.cpp.i
.PHONY : src/GameEngine/Mesh.cpp.i

src/GameEngine/Mesh.s: src/GameEngine/Mesh.cpp.s
.PHONY : src/GameEngine/Mesh.s

# target to generate assembly for a file
src/GameEngine/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Mesh.cpp.s
.PHONY : src/GameEngine/Mesh.cpp.s

src/GameEngine/MeshManager.o: src/GameEngine/MeshManager.cpp.o
.PHONY : src/GameEngine/MeshManager.o

# target to build an object file
src/GameEngine/MeshManager.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/MeshManager.cpp.o
.PHONY : src/GameEngine/MeshManager.cpp.o

src/GameEngine/MeshManager.i: src/GameEngine/MeshManager.cpp.i
.PHONY : src/GameEngine/MeshManager.i

# target to preprocess a source file
src/GameEngine/MeshManager.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/MeshManager.cpp.i
.PHONY : src/GameEngine/MeshManager.cpp.i

src/GameEngine/MeshManager.s: src/GameEngine/MeshManager.cpp.s
.PHONY : src/GameEngine/MeshManager.s

# target to generate assembly for a file
src/GameEngine/MeshManager.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/MeshManager.cpp.s
.PHONY : src/GameEngine/MeshManager.cpp.s

src/GameEngine/Renderer.o: src/GameEngine/Renderer.cpp.o
.PHONY : src/GameEngine/Renderer.o

# target to build an object file
src/GameEngine/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Renderer.cpp.o
.PHONY : src/GameEngine/Renderer.cpp.o

src/GameEngine/Renderer.i: src/GameEngine/Renderer.cpp.i
.PHONY : src/GameEngine/Renderer.i

# target to preprocess a source file
src/GameEngine/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Renderer.cpp.i
.PHONY : src/GameEngine/Renderer.cpp.i

src/GameEngine/Renderer.s: src/GameEngine/Renderer.cpp.s
.PHONY : src/GameEngine/Renderer.s

# target to generate assembly for a file
src/GameEngine/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Renderer.cpp.s
.PHONY : src/GameEngine/Renderer.cpp.s

src/GameEngine/Triangle.o: src/GameEngine/Triangle.cpp.o
.PHONY : src/GameEngine/Triangle.o

# target to build an object file
src/GameEngine/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Triangle.cpp.o
.PHONY : src/GameEngine/Triangle.cpp.o

src/GameEngine/Triangle.i: src/GameEngine/Triangle.cpp.i
.PHONY : src/GameEngine/Triangle.i

# target to preprocess a source file
src/GameEngine/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Triangle.cpp.i
.PHONY : src/GameEngine/Triangle.cpp.i

src/GameEngine/Triangle.s: src/GameEngine/Triangle.cpp.s
.PHONY : src/GameEngine/Triangle.s

# target to generate assembly for a file
src/GameEngine/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Triangle.cpp.s
.PHONY : src/GameEngine/Triangle.cpp.s

src/GameEngine/VarManager.o: src/GameEngine/VarManager.cpp.o
.PHONY : src/GameEngine/VarManager.o

# target to build an object file
src/GameEngine/VarManager.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/VarManager.cpp.o
.PHONY : src/GameEngine/VarManager.cpp.o

src/GameEngine/VarManager.i: src/GameEngine/VarManager.cpp.i
.PHONY : src/GameEngine/VarManager.i

# target to preprocess a source file
src/GameEngine/VarManager.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/VarManager.cpp.i
.PHONY : src/GameEngine/VarManager.cpp.i

src/GameEngine/VarManager.s: src/GameEngine/VarManager.cpp.s
.PHONY : src/GameEngine/VarManager.s

# target to generate assembly for a file
src/GameEngine/VarManager.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/VarManager.cpp.s
.PHONY : src/GameEngine/VarManager.cpp.s

src/GameEngine/Vec2.o: src/GameEngine/Vec2.cpp.o
.PHONY : src/GameEngine/Vec2.o

# target to build an object file
src/GameEngine/Vec2.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vec2.cpp.o
.PHONY : src/GameEngine/Vec2.cpp.o

src/GameEngine/Vec2.i: src/GameEngine/Vec2.cpp.i
.PHONY : src/GameEngine/Vec2.i

# target to preprocess a source file
src/GameEngine/Vec2.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vec2.cpp.i
.PHONY : src/GameEngine/Vec2.cpp.i

src/GameEngine/Vec2.s: src/GameEngine/Vec2.cpp.s
.PHONY : src/GameEngine/Vec2.s

# target to generate assembly for a file
src/GameEngine/Vec2.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vec2.cpp.s
.PHONY : src/GameEngine/Vec2.cpp.s

src/GameEngine/Vec3.o: src/GameEngine/Vec3.cpp.o
.PHONY : src/GameEngine/Vec3.o

# target to build an object file
src/GameEngine/Vec3.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vec3.cpp.o
.PHONY : src/GameEngine/Vec3.cpp.o

src/GameEngine/Vec3.i: src/GameEngine/Vec3.cpp.i
.PHONY : src/GameEngine/Vec3.i

# target to preprocess a source file
src/GameEngine/Vec3.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vec3.cpp.i
.PHONY : src/GameEngine/Vec3.cpp.i

src/GameEngine/Vec3.s: src/GameEngine/Vec3.cpp.s
.PHONY : src/GameEngine/Vec3.s

# target to generate assembly for a file
src/GameEngine/Vec3.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vec3.cpp.s
.PHONY : src/GameEngine/Vec3.cpp.s

src/GameEngine/Vertex.o: src/GameEngine/Vertex.cpp.o
.PHONY : src/GameEngine/Vertex.o

# target to build an object file
src/GameEngine/Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vertex.cpp.o
.PHONY : src/GameEngine/Vertex.cpp.o

src/GameEngine/Vertex.i: src/GameEngine/Vertex.cpp.i
.PHONY : src/GameEngine/Vertex.i

# target to preprocess a source file
src/GameEngine/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vertex.cpp.i
.PHONY : src/GameEngine/Vertex.cpp.i

src/GameEngine/Vertex.s: src/GameEngine/Vertex.cpp.s
.PHONY : src/GameEngine/Vertex.s

# target to generate assembly for a file
src/GameEngine/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine.dir/build.make CMakeFiles/GameEngine.dir/src/GameEngine/Vertex.cpp.s
.PHONY : src/GameEngine/Vertex.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GameEngine"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/GameEngine/EngineInstance.o"
	@echo "... src/GameEngine/EngineInstance.i"
	@echo "... src/GameEngine/EngineInstance.s"
	@echo "... src/GameEngine/Logger.o"
	@echo "... src/GameEngine/Logger.i"
	@echo "... src/GameEngine/Logger.s"
	@echo "... src/GameEngine/Material.o"
	@echo "... src/GameEngine/Material.i"
	@echo "... src/GameEngine/Material.s"
	@echo "... src/GameEngine/MaterialManager.o"
	@echo "... src/GameEngine/MaterialManager.i"
	@echo "... src/GameEngine/MaterialManager.s"
	@echo "... src/GameEngine/Mesh.o"
	@echo "... src/GameEngine/Mesh.i"
	@echo "... src/GameEngine/Mesh.s"
	@echo "... src/GameEngine/MeshManager.o"
	@echo "... src/GameEngine/MeshManager.i"
	@echo "... src/GameEngine/MeshManager.s"
	@echo "... src/GameEngine/Renderer.o"
	@echo "... src/GameEngine/Renderer.i"
	@echo "... src/GameEngine/Renderer.s"
	@echo "... src/GameEngine/Triangle.o"
	@echo "... src/GameEngine/Triangle.i"
	@echo "... src/GameEngine/Triangle.s"
	@echo "... src/GameEngine/VarManager.o"
	@echo "... src/GameEngine/VarManager.i"
	@echo "... src/GameEngine/VarManager.s"
	@echo "... src/GameEngine/Vec2.o"
	@echo "... src/GameEngine/Vec2.i"
	@echo "... src/GameEngine/Vec2.s"
	@echo "... src/GameEngine/Vec3.o"
	@echo "... src/GameEngine/Vec3.i"
	@echo "... src/GameEngine/Vec3.s"
	@echo "... src/GameEngine/Vertex.o"
	@echo "... src/GameEngine/Vertex.i"
	@echo "... src/GameEngine/Vertex.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

